
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #  控制注册中心在注册中心的页面中不显示 false
    register-with-eureka: false
  server:
#  关掉注册中心页面上因为程序重复报红，注意在开发环境可以注释，但是生产环境必须打开
    enable-self-preservation: false
spring:
  application:
#    设置注册中心中显示的名字
    name: eureka
management:
  context-path: /
server:
  port: 8761